Repository Soen390-Pathfinders/SOEN390_PathFinders, pull requests merged in 2025-02, with the labels that each got.

#178 1. Added the drawerr item for Concordia Shuttle
  frontend/app/_layout.tsx
  frontend/app/components/ui/ConcordiaShuttleTimes.tsx
  frontend/app/screens/ConcordiaShuttle.tsx
  frontend/assets/images/chronometer.png
Labels: sprint 3

#180 Aman shuttle bus
  frontend/app/_layout.tsx
  frontend/app/components/ui/ConcordiaShuttleTimes.tsx
  frontend/app/screens/ConcordiaShuttle.tsx
  frontend/assets/images/bus.png
Labels: enhancement

#182 OutdoorDirection - Refactoring
  frontend/app/components/ui/DirectionFields.tsx
  frontend/app/hooks/useDirectionLogic.ts
  frontend/app/screens/OutdoorDirections.tsx
Labels: bug, enhancement, sprint 3

#186 Fixed the IOS bug by switching to PROVIDER_DEFAULT and the toggle button issue
  frontend/app/components/maps/OutdoorMap.tsx
  frontend/app/screens/CampusMap.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: bug, enhancement
